# Generated by Django 4.0.4 on 2022-04-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0002_alter_upcomingmatch_options_truescore_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='match',
        ),
    ]
