# Generated by Django 4.0.3 on 2022-03-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Match',
        ),
    ]
